name: click_charger
description: Clicker game made with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.1
  cupertino_icons: ^1.0.1
  json_annotation: ^3.0.0
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/